name: docker

on:
  push:
    branches:
      - master
    tags:
      - \d+\.\d+\.\d+

env:
  IMAGE: dstarikov/smarthome

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build & push image
        run: |
          # strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # use docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          docker buildx build --push \
            --tag $IMAGE:$VERSION \
            --platform linux/amd64,linux/arm64 .
